name: React CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master 

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up React
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn install
      - run: yarn run build
      - run: yarn test
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
